/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package formularios;

import clases.ClsGlobales;

/**
 *
 * @author Juan Diego Pacheco
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        this.lblCorreo.setText(ClsGlobales.usuarioGlobal.getCorreo());
        this.mnuUsuariosActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnClientes = new javax.swing.JButton();
        btnConductores = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnPaqueteria = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        mnuProcesos = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuConductores = new javax.swing.JMenuItem();
        mnuVehiculos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuPaqueteria = new javax.swing.JMenuItem();
        mnuInformacion = new javax.swing.JMenu();
        mnuAcerca = new javax.swing.JMenuItem();
        mnuSistema = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de gestion de paqueteria");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar-128x128-456320.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("--");

        btnClientes.setBackground(new java.awt.Color(0, 102, 102));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/People.png"))); // NOI18N
        btnClientes.setText("   Mantenimiento de clientes");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnConductores.setBackground(new java.awt.Color(0, 102, 102));
        btnConductores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConductores.setForeground(new java.awt.Color(255, 255, 255));
        btnConductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boss.png"))); // NOI18N
        btnConductores.setText("   Mantenimiento de conductores");
        btnConductores.setBorderPainted(false);
        btnConductores.setContentAreaFilled(false);
        btnConductores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConductores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnVehiculos.setBackground(new java.awt.Color(0, 102, 102));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delivery.png"))); // NOI18N
        btnVehiculos.setText("   Mantenimiento de vehiculos");
        btnVehiculos.setBorderPainted(false);
        btnVehiculos.setContentAreaFilled(false);
        btnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPaqueteria.setBackground(new java.awt.Color(0, 102, 102));
        btnPaqueteria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPaqueteria.setForeground(new java.awt.Color(255, 255, 255));
        btnPaqueteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja3.png"))); // NOI18N
        btnPaqueteria.setText("   Administracion de paqueteria");
        btnPaqueteria.setBorderPainted(false);
        btnPaqueteria.setContentAreaFilled(false);
        btnPaqueteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaqueteria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnUsuarios.setBackground(new java.awt.Color(0, 102, 102));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Text.png"))); // NOI18N
        btnUsuarios.setText("   Listado de usuarios");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(0, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Abort.png"))); // NOI18N
        btnCerrar.setText("   Cerrar sesion");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPaqueteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConductores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaqueteria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuProcesos.setMnemonic('f');
        mnuProcesos.setText("Procesos");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuClientes.setMnemonic('o');
        mnuClientes.setText("Mantenimiento de clientes");
        mnuClientes.addActionListener(this::mnuClientesActionPerformed);
        mnuProcesos.add(mnuClientes);

        mnuConductores.setMnemonic('s');
        mnuConductores.setText("Mantenimiento de conductores");
        mnuProcesos.add(mnuConductores);

        mnuVehiculos.setMnemonic('a');
        mnuVehiculos.setText("Mantenimiento de vehiculos");
        mnuProcesos.add(mnuVehiculos);
        mnuProcesos.add(jSeparator3);

        mnuPaqueteria.setMnemonic('x');
        mnuPaqueteria.setText("Administracion de paqueteria");
        mnuPaqueteria.addActionListener(this::mnuPaqueteriaActionPerformed);
        mnuProcesos.add(mnuPaqueteria);

        menuBar.add(mnuProcesos);

        mnuInformacion.setMnemonic('e');
        mnuInformacion.setText("Informacion");

        mnuAcerca.setMnemonic('t');
        mnuAcerca.setText("Arcerda de...");
        mnuInformacion.add(mnuAcerca);

        menuBar.add(mnuInformacion);

        mnuSistema.setMnemonic('h');
        mnuSistema.setText("Sistema");

        mnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuUsuarios.setMnemonic('c');
        mnuUsuarios.setText("Listado de usuarios");
        mnuUsuarios.addActionListener(this::mnuUsuariosActionPerformed);
        mnuSistema.add(mnuUsuarios);

        mnuCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuCerrar.setMnemonic('a');
        mnuCerrar.setText("Cerrar sesion");
        mnuCerrar.addActionListener(this::mnuCerrarActionPerformed);
        mnuSistema.add(mnuCerrar);

        menuBar.add(mnuSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPaqueteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPaqueteriaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuPaqueteriaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        FrmLogin flogin = new FrmLogin();
        flogin.show();
    }//GEN-LAST:event_formWindowClosed

    private void mnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuCerrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.mnuCerrarActionPerformed(null);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        
        ClsGlobales.fUsuarios = new IFrmUsuarios();
        
        this.desktopPane.removeAll();
        this.desktopPane.add(ClsGlobales.fUsuarios);
        ClsGlobales.fUsuarios.setVisible(true);
        
        try{
            ClsGlobales.fUsuarios.setMaximum(true);
        }catch(Exception e){}
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        this.mnuUsuariosActionPerformed(null);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        
        ClsGlobales.fClientes = new IFrmClientes();
        
        this.desktopPane.removeAll();
        this.desktopPane.add(ClsGlobales.fClientes);
        ClsGlobales.fClientes.setVisible(true);
        
        try{
            ClsGlobales.fClientes.setMaximum(true);
        }catch(Exception e){}
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        this.mnuClientesActionPerformed(null);
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConductores;
    private javax.swing.JButton btnPaqueteria;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenuItem mnuCerrar;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuConductores;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenuItem mnuPaqueteria;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JMenuItem mnuVehiculos;
    // End of variables declaration//GEN-END:variables

}
